{% set name = "ternary-diagram" %}
{% set version = "3.2.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ternary_diagram-{{ version }}.tar.gz
  sha256: 9c58793619dd84a08c3d5c2aea08c91b53c6766d515edbc34d4b728518e1f331

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - matplotlib-base

test:
  imports:
    - ternary_diagram
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/yu9824/ternary_diagram/
  summary: This package makes it easier for you to draw beautiful ternary diagram without pymatgen.
  dev_url: http://github.com/yu9824/ternary_diagram/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
