{% set name = "ternary-diagram" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ternary_diagram-{{ version }}.tar.gz
  sha256: f54a80c093a24126c64ecec24f723c6863cd138b8e71e7cef81ef46d50b35647

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  imports:
    - ternary_diagram
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/yu9824/ternary_diagram/
  summary: This package makes it easier for you to draw beautiful ternary diagram without pymatgen.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
